services:
  app:
    image: elaxdev/nihongo-tracker:latest
    ports:
      - "3000:3000"
    env_file:
      - Backend/.env
    depends_on:
      mongo:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    volumes:
      - ./Backend/.env:/app/Backend/.env:ro
    restart: always

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  migration:
    image: elaxdev/nihongo-tracker:latest
    env_file:
      - Backend/.env
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    command: >
      sh -c "cd /app/Backend && 
             npm run migrate:indexes:prod && 
             echo 'Migration completed successfully'"
    restart: "no"

volumes:
  mongo-data:
